---
- name: Install latest Neovim
  hosts: local
  connection: local
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install software-properties-common
      ansible.builtin.apt:
        name: software-properties-common
        state: present

    - name: Download and extract Neovim
      ansible.builtin.unarchive:
        src: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
        dest: /opt/
        remote_src: true

    - name: Configure Neovim alternative
      community.general.alternatives:
        name: nvim
        path: /opt/nvim-linux-x86_64/bin/nvim
        link: /usr/bin/nvim
        priority: 100
        state: present
